[package]
name = "diesel_compile_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[workspace]

[dependencies]
diesel = { version = "1.1.0", default-features = false, features = ["extras", "sqlite", "postgres", "mysql"] }
compiletest_rs = "=0.3.3"

[replace]
"diesel:1.1.1" = { path = "../diesel" }
"diesel_derives:1.1.0" = { path = "../diesel_derives" }
